[platformio]
default_envs = unihiker_k10

[env:unihiker_k10]
platform = https://github.com/DFRobot/platform-unihiker.git#508e31875ad92205bf946e28570fb78fc01ceb2e
board = unihiker_k10
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/DFRobot/DFRobot_MatrixLidar.git#058db6ca7447ffc79ea3d31245e9057ccceb4cfc
